name: Linux Container Dash (Flask) Python Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: greenkid7.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t greenkid7.azurecr.io/greenkid7:${{ github.sha }}
        docker push greenkid7.azurecr.io/greenkid7:${{ github.sha }}

    - name: Building web app
      uses: azure/appservice-build@v2

    - name: Deploy web App using GH Action azure/webapps-deploy     
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GreenKid7'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'greenkid7.azurecr.io/greenkid7:${{ github.sha }}'